### PR TITLE
SNI (Server Name Indication) for Ssl.client

### PR DESCRIPTION
**Pull request by pdonadeo**
Ssl.client can set the hostname parameter of the SNI TLS extension.

### CODE REVIEW

**Comment by tari3x** [comment]
Looks good. I wasn't able to find info about what version this function is available from, but I guess we'll see if someone complains. I'll merge this internally.

**Comment by yminsky** [comment]
@tari3x Has this been resolved? If so, can we close the PR?

**Comment by hhugo** [comment]
These changes were merged already. Closing.

**Pull request closed without merging**
